name: Test

on:
  push:
    branches:
      - $default-branch
      - development
      - master
  # Run tests for any PRs
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    # The host should always be linux
    runs-on: ubuntu-latest
    name: Running tests on ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        distro:
          - 'centos:7'
          - 'centos:8'
          - 'fedora:32'
          - 'fedora:33'
          - 'fedora:34'
          - 'fedora:35'
        include:
          - distro: 'fedora:35'
            pre: >-
              dnf install -y sudo perl-Module-Install perl-Readonly perl-Monitoring-Plugin perl-Perl-Critic rpm-build perl-Net-DNS perl-Data-Validate-Domain perl-Net-IP perl-Data-Validate-IP
          - distro: 'fedora:34'
            pre: >-
              dnf install -y sudo perl-Module-Install perl-Readonly perl-Monitoring-Plugin perl-Perl-Critic rpm-build perl-Net-DNS perl-Data-Validate-Domain perl-Net-IP perl-Data-Validate-IP
          - distro: 'fedora:33'
            pre: >-
              dnf install -y sudo perl-Module-Install perl-Readonly perl-Monitoring-Plugin perl-Perl-Critic rpm-build perl-Net-DNS perl-Data-Validate-Domain perl-Net-IP perl-Data-Validate-IP
          - distro: 'fedora:32'
            pre: >-
              dnf install -y sudo perl-Module-Install perl-Readonly perl-Monitoring-Plugin perl-Perl-Critic rpm-build perl-Net-DNS perl-Data-Validate-Domain perl-Net-IP perl-Data-Validate-IP
          - distro: 'centos:7'
            pre: >-
              yum install -y epel-release &&
              yum install -y sudo perl-Module-Install perl-Readonly perl-Monitoring-Plugin perl-Test-Simple perl-Perl-Critic rpm-build perl-Net-DNS perl-Net-IP perl-Data-Validate-IP perl-App-cpanminus &&
              sudo cpanm Data::Validate::Domain
          - distro: 'centos:8'
            pre: >-
              dnf install -y sudo dnf-plugins-core epel-release &&
              sudo dnf config-manager --set-enabled powertools &&
              dnf install -y perl perl-Module-Install  perl-Readonly perl-Monitoring-Plugin perl-Perl-Critic rpm-build perl-Net-DNS perl-Net-IP perl-Data-Validate-IP perl-App-cpanminus &&
              sudo cpanm Data::Validate::Domain
    steps:
      - name: Git clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run the tests on ${{ matrix.distro }}
        env:
          PRE: ${{ matrix.pre }}
        run: |
          echo $PRE > ./prep-cmd.sh
          docker run --network host -w /check_rbl -v ${PWD}:/check_rbl ${{ matrix.distro }} \
              /bin/sh -c 'sh ./prep-cmd.sh \
              && uname -a \
              && perl Makefile.PL \
              && make test \
              && ./test_script.sh \
              && ./check_distribution.sh \
              && ./build_rpm.sh'
